theme: minima
title: E-commerce Website
author: umerbl
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 This website has a seprate fan base.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
