theme: minima
title: E-commerce 
author: umerbl
email: umer.saif0009@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A website that allows people to buy and sell physical goods, services, and digital products over the internet rather than at a brick-and-mortar location.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
