---
title: "Welcome to my blog"
date: 2019-01-20
---
theme: minima.
title: Developer
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This site is very popular around the world because it makes a very good relationship among customers and people think positive about it.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
